USE Senai_Pizzarias
SELECT * FROM USUARIO
SELECT * FROM PIZZARIAS
SELECT * FROM CATEGORIA_PRECO

SELECT P.ID_PIZZARIA, P.NOME, P.ENDERECO, P.TELEFONE_COMERCIAL, P.OPCAO_VEGANA, CP.CATEGORIA
FROM PIZZARIAS P INNER JOIN CATEGORIA_PRECO CP ON CP.ID_CATEGORIA = P.CATEGORIA_DO_PRECO 
